color = ""

[default]
  account_id = "acct_1IeVDUBeIT5ezO68"
  device_name = "starbound"
  display_name = "colabmerch.com.au"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_51IeVDUBeIT5ezO68qyO3BpzdHYmF7C5FDiLmgRioV4PTB8eO38ZINw0QtK47kDnhK0lqdxP3ClkAYYEVXHtdsyrP00QIplCXv0"
  test_mode_api_key = "rk_test_51IeVDUBeIT5ezO6826e3uLTQpL1FuzGzy51Arf5OyaMdOSkvdafIvrG43XW2QFBPitjihpKXE7yu4ax1x0idyebe00qWeq9rSY"
  test_mode_publishable_key = "pk_test_51IeVDUBeIT5ezO68L0T9FOWtOg4twVwQI3PSEtacknmwdltv3LSatyzFbFMXej19DTlkf2xVwBGSq1MW4oK0tp5V00DRpZXu7s"
